<?php
/**
 * Fast Tunnel — Configuration File
 * This file is auto-generated by the installer.
 * Do NOT edit this file manually unless you know what you are doing.
 */

define('DB_HOST', '%%DB_HOST%%');
define('DB_PORT', '%%DB_PORT%%');
define('DB_USER', '%%DB_USER%%');
define('DB_PASS', '%%DB_PASS%%');
define('DB_NAME', '%%DB_NAME%%');
define('ENCRYPTION_KEY', '%%ENCRYPTION_KEY%%');
define('CSRF_SECRET', 'ft_csrf_' . md5(__DIR__));
define('FT_LICENSE_KEY', '%%LICENSE_KEY%%');
define('FT_LICENSE_EMAIL', '%%LICENSE_EMAIL%%');

function getAppDb(): PDO {
    static $pdo = null;
    if ($pdo === null) {
        $dsn = 'mysql:host=' . DB_HOST . ';port=' . DB_PORT . ';dbname=' . DB_NAME . ';charset=utf8mb4';
        $pdo = new PDO($dsn, DB_USER, DB_PASS, [
            PDO::ATTR_ERRMODE        => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES   => false,
        ]);
    }
    return $pdo;
}
